version: "3.9"

services:
    frontend:
        container_name: tradeoffer-frontend
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            backend:
                condition: service_healthy
        ports:
            - "3002:3002"
        environment:
            SERVER_ORIGIN: http://localhost:3001
            
    backend:
        container_name: tradeoffer-backend
        build:
            context: backend
            dockerfile: Dockerfile
        ports:
            - "3001:3001"
        environment:
            MYSQL_HOST: db
            JWT_SECRET_TOKEN: MyToken
            CORS_ORIGIN_REGEX: http([s])?:\/\/localhost
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
            test: curl --fail http://localhost:3001 || exit 1
            interval: 5s
            timeout: 50s
            retries: 10
    db: 
        container_name: tradeoffer-db
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=tradeoffer_db
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
        healthcheck:
            test: '/usr/bin/mysql --user=root --password=root --execute "SELECT 1;"'
            interval: 5s
            timeout: 50s
            retries: 10
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        restart: on-failure:5

    adminer:
        image: adminer
        container_name: tradeoffer-adminer
        restart: always
        ports:
            - 8080:8080
            
volumes:
  mysql_data:
